# Site settings
title: Wanderer
email: lauren.l.dev@gmail.com
url: https://laurenball.github.io
description: 'Portfolio/Blog'
keywords: ""
skills: "it's weird that this is in the metadata right"
meta_author: Ball Lauren

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Lauren Ball
  location: Location
  social: Around the Web

social:
  - title: github
    url: https://github.com/laurenball
  - title: linkedin
    url: https://www.linkedin.com/in/lauren-ball/

# Credits content
credits: 'Theme foundation by <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

plugins:
  - jekyll-data
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
